COLOR_PRIMARIO="#ffffff";
COLOR_SECUNDARIO="#00B17D";
COLOR_WHITE = "#3b3b3b"
COLOR_INPUT = '#E0E0E0';
COLOR_BLUE= '#0083BE'
COLOR_VERDE= '#006157'
export default{
    COLOR_PRIMARIO,
    COLOR_SECUNDARIO,
    COLOR_WHITE,
    COLOR_INPUT,
    COLOR_BLUE,
    COLOR_VERDE
}