COLOR_PRIMARIO="#ffffff";
COLOR_SECUNDARIO="#00B17D";
COLOR_WHITE = "#3b3b3b";
COLOR_INPUT = '#E0E0E0';
COLOR_BLUE= '#0083BE';
COLOR_VERDE= '#006157';
COLOR_NEGRO= '#00000p0'
COLOR_FONDO = '#f6f8f7'
COLOR_ICONOS = '#616161'

export default{
    COLOR_PRIMARIO,
    COLOR_SECUNDARIO,
    COLOR_WHITE,
    COLOR_INPUT,
    COLOR_BLUE,
    COLOR_VERDE,
    COLOR_NEGRO,
    COLOR_FONDO,
    COLOR_ICONOS
}